# ----------- STAGE 1: build -----------
FROM node:20-alpine AS builder

WORKDIR /app

COPY apps/frontend/package*.json ./
RUN npm install

COPY apps/frontend ./
RUN npm run build


# ----------- STAGE 2: production -----------
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf

# ИСПРАВЛЕННЫЙ ПУТЬ (указываем путь от корня контекста)
COPY apps/frontend/nginx/app.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
