# Конфиг для Фронтенда
server {
    listen 80;
    server_name app.mf-services.online;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        # Перенаправление на HTTPS после получения сертификатов
        # return 301 https://$host$request_uri; 
        
        proxy_pass http://frontend:80; # Добавлен порт внутри сети Docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}